[theme]
primaryColor = "#0F4C81"
backgroundColor = "#EEF2F7"
secondaryBackgroundColor = "#E1EBF6"
textColor = "#0A2540"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 1
