[theme]
base = "light"
primaryColor = "#FF9137"
backgroundColor = "#F7F8F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 1
