[theme]
base = "light"
primaryColor = "#082F49"
backgroundColor = "#F7F5F1"
secondaryBackgroundColor = "#EAF4FB"
textColor = "#111827"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 1
